### ISSUE TITLE
RedisDatabase StringSet or StringGet - No connection is active/available to service this operation

### ISSUE THREAD

**Issue by tomasfabian** [StackExchange/StackExchange.Redis#1424]
Hi,
I'm trying to get or set a string key from redis database after OnConnectionRestored, but the command sometimes failes:
```
    public void Connect()
    {
      var configuration = new ConfigurationOptions
      {
        AbortOnConnectFail = false,
        ConnectTimeout = 3000,
        SyncTimeout = 5000,
        KeepAlive = 180,
        EndPoints =
        {
          {
            url, Port
          }
        }
      };

      var connectionMultiplexer = ConnectionMultiplexer.Connect(configuration);
      connectionMultiplexer.GetDatabase();

      connectionMultiplexer.ConnectionRestored += OnConnectionRestored;

      var subscriber = connectionMultiplexer.GetSubscriber();
    }    

    private void OnConnectionRestored(object sender, ConnectionFailedEventArgs args)
    {
      var connectionMultiplexer = (ConnectionMultiplexer) sender;
      if (connectionMultiplexer.IsConnected)
      {
        var redisDatabase = connectionMultiplexer.GetDatabase();

        var setStringResult = redisDatabase.StringSet(new[]
        {
          new KeyValuePair<RedisKey, RedisValue>("key", "value")
        });
      }
    }
```

StackExchange.Redis.RedisConnectionException: 'No connection is active/available to service this operation: SET key, mc: 1/1/0, mgr: 10 of 10 available, clientName: FABIAN-PC, IOCP: (Busy=0,Free=1000,Min=8,Max=1000), WORKER: (Busy=1,Free=32766,Min=8,Max=32767), v: 2.1.30.38891'

FailureType = UnableToResolvePhysicalConnection

   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 2575
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()_

Is it possible to observe somehow IDatabase IsConnected? Or is there a problem somewhere else?

Thank you, Tomas

**Comment by tomasfabian** [comment]
Same happens OnConnectionRestored with:
`subscriber.PublishAsync(redisChannel, redisValue, commandFlags);`

No connection is active/available to service this operation: PUBLISH Product-Status, mc: 1/1/0, mgr: 9 of 10 available, clientName: FABIAN-PC, IOCP: (Busy=2,Free=998,Min=8,Max=1000), WORKER: (Busy=4,Free=32763,Min=8,Max=32767), v: 2.1.30.38891

**Comment by ya-breeze** [comment]
We see same issue on 2.1.28 on framework 4.7.2.
We use redis cluster with several shards and usually this error starts to happen after HashSlotMoved event and usually it affects one/two shards only, i.e. requests to other shards work normally.
What would you recommend us to do to investigate it further?

**Comment by petro2050** [comment]
@mgravell I'm getting a similar exception as well. This seems to be happening every once in a while.
```
StackExchange.Redis.RedisConnectionException: No connection is active/available to service this operation: GET d4551e38-26e8-48e8-9952-7f91e162e975:explore/get:637231860000000000; UnableToConnect on myappdev.redis.cache.windows.net:6380/Interactive, Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 5s ago, last-write: 5s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 5s ago, v: 2.1.30.38891, mc: 1/1/0, mgr: 10 of 10 available, clientName: RD281878EF044A, IOCP: (Busy=0,Free=1000,Min=500,Max=1000), WORKER: (Busy=4,Free=32763,Min=500,Max=32767), v: 2.1.30.38891
 ---> StackExchange.Redis.RedisConnectionException: UnableToConnect on myappdev.redis.cache.windows.net:6380/Interactive, Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 5s ago, last-write: 5s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 5s ago, v: 2.1.30.38891
   at StackExchange.Redis.TaskExtensions.TimeoutAfter(Task task, Int32 timeoutMs)
   at StackExchange.Redis.ConnectionMultiplexer.WaitAllIgnoreErrorsAsync(Task[] tasks, Int32 timeoutMilliseconds, LogProxy log, String caller, Int32 callerLineNumber)
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server)
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server)
   at StackExchange.Redis.RedisDatabase.StringGet(RedisKey key, CommandFlags flags)
```

**Comment by msx752** [comment]
i am getting frequently timeout error and after that i am getting error like **no connection is active** , i have enabled **preventthreadsafe** if i dont do that, application throws much more timeout errors. 


firstly getting timeout error
```
Timeout performing GET (5000ms), active: LLEN ProfileVerificationQueue,
next: LLEN AutoDiscordMsgRemove ** possible thread-theft indicated; 
see https://stackexchange.github.io/StackExchange.Redis/ThreadTheft ** ,
inst: 0, qu: 0, qs: 6, aw: False, rs: CompletePendingMessageSync, 
ws: Idle, in: 0, in-pipe: 983, out-pipe: 0, 
serverEndpoint: linuxserver:6379, mc: 1/1/0, mgr: 8 of 10 available,
clientName: Redis CLient, IOCP: (Busy=0,Free=1000,Min=2,Max=1000),
WORKER: (Busy=2,Free=98,Min=1,Max=100), v: 2.1.28.64774 
(Please take a look at this article for some common client-side issues
that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)
```
secondly this type of errors

```
Redis: Connection is restored, type: None
Redis: Connection is failed, type: SocketClosed
Redis: Connection is failed, type: UnableToConnect
Redis: Connection is failed, type: SocketClosed
Redis: Connection is failed, type: SocketClosed
Redis: Connection is failed, type: UnableToConnect
etc...
```
thirdly this error will popup
```
No connection is active/available to service this operation: LLEN AutoDiscordMsgRemove; 
SocketClosed (ReadEndOfStream, last-recv: 0) on linuxserver:6379/Interactive,
Idle/MarkProcessed, last: LLEN, origin: ReadFromPipe, outstanding: 0,
last-read: 0s ago, last-write: 0s ago, keep-alive: 60s, state: ConnectedEstablished, 
mgr: 8 of 10 available, in: 0, in-pipe: 0, out-pipe: 0, last-heartbeat: 1s ago, 
last-mbeat: 0s ago, global: 0s ago, v: 2.1.28.64774, mc: 1/1/0, mgr: 10 of 10 available, 
clientName: Redis CLient, IOCP: (Busy=0,Free=1000,Min=2,Max=1000), 
WORKER: (Busy=3,Free=97,Min=1,Max=100), v: 2.1.28.64774
```
lastly
```
Redis: Connection is restored, type: None
Redis: Connection is restored, type: None
Redis: Connection is restored, type: None
Redis: Connection is restored, type: None
```
after a while application working well then when frequrently GET/SET comes it repeats same things

**Comment by DarthSonic** [comment]
We have similar problems: On start of application (ASP.NET 4.7.1, MVC, C#) we get "No connection is active/available to service this operation" error one time. After that connections are working. But several times a day we get "Timeout performing GET" exceptions but redis does not log any slow operations itself.

**Comment by dpak1170** [comment]
We are also seeing this...we have a retry mechanism and my hunch is buffers are getting filled up making the command not even reach redis and incorrectly flagged as a timeout exception. We are not seeing any memory leaks in our app though...

**Comment by nsalikhov** [comment]
We are getting this exception very often:
`StackExchange.Redis.RedisConnectionException: It was not possible to connect to the redis server(s). UnableToConnect on redis:6379/Interactive, Initializing/NotStarted, last: GET, origin: BeginConnectAsync, outstanding: 0, last-read: 0s ago, last-write: 0s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat:`
Probably, we can count exceptions and re-create ConnectionMultiplexer... but it seems it should be fixed inside library.
@mgravell, is there any ideas on this issue?

**Comment by dpak1170** [comment]
In our tests it is happening because either:

1. The connection limit has been reached on the redis box. Since we are using a dynamic connection pool that shrinks and grows based on demand. If the connection limit has increased then the redis box will not accept new connections. 
2. Client network throttling via proxies or firewall...this was a local firewall issue so the fix was very straightforward.

We have been able to get around it by setting the timeout to be greater than default timeout of 5 secs and added connectRetry to 10.

**Comment by kubusCdr** [comment]
In my case (original post) it happens because connectionMultiplexer.ConnectionRestored announces connectionMultiplexer.IsConnected, but the redisDatabase is still not available. They are probably not synced. In case they are not related, is it possible to add redisDatabase.ConnectionRestored ?  
I'm using retry action after a delay for now.

**Comment by nsalikhov** [comment]
`Probably, we can count exceptions and re-create ConnectionMultiplexer... but it seems it should be fixed inside library.`
We implemented this logic and pooling - but with no luck - still getting high error-rate. Probably, this issue appears on some high load - we have 13-15k RPS and sentinel redis with 3 nodes - other projects with small load are works fine.

**Comment by NickCraver** [comment]
Thanks for the report here - this issue is greatly improved and should no longer be an issue in the 2.5 release - see the changes in #1947 for fixes around this!
