### ISSUE TITLE
Library not working in ASP.NET MVC 5 pipeline (.NET 4.7.2)

### ISSUE THREAD

**Issue by saciervo** [StackExchange/StackExchange.Redis#1436]
Repo to reproduce the problem: https://github.com/saciervo/Try.Redis472, just use your own Redis connection string [here](https://github.com/saciervo/Try.Redis472/blob/d387a82ddb4969ad04557a7a0ece17db78040a7c/Try.Redis472.Autofac.DependencyResolution/AutofacInstaller.cs#L18). I used Azure Cache to reproduce, I tried it both via SSL and Non-SSL.

Apparently there is a problem when using StackExchange.Redis in MVC5 applications. The repository mentioned above has two applications: a [console application](https://github.com/saciervo/Try.Redis472/tree/master/Try.Redis472.Autofac.Console) and a [web application](https://github.com/saciervo/Try.Redis472/tree/master/Try.Redis472.Autofac.Web). Both use the same [DI configuration with Autofac](https://github.com/saciervo/Try.Redis472/blob/master/Try.Redis472.Autofac.DependencyResolution/AutofacInstaller.cs) and both use the [same service](https://github.com/saciervo/Try.Redis472/blob/master/Try.Redis472.Services/TestService.cs) that accesses the Redis Cache [via Microsoft.Extensions.Caching.Redis](https://github.com/saciervo/Try.Redis472/blob/d387a82ddb4969ad04557a7a0ece17db78040a7c/Try.Redis472.Services/TestService.cs#L18).

The [console application works](https://github.com/saciervo/Try.Redis472/blob/d387a82ddb4969ad04557a7a0ece17db78040a7c/Try.Redis472.Autofac.Console/Program.cs#L26), the [web application does not](https://github.com/saciervo/Try.Redis472/blob/d387a82ddb4969ad04557a7a0ece17db78040a7c/Try.Redis472.Autofac.Web/Controllers/HomeController.cs#L30). Somehow it seems that the connection cannot be established correctly. But there is no timeout... when debugging the application it just gets stuck [as soon as a Redis connection is required](https://github.com/saciervo/Try.Redis472/blob/d387a82ddb4969ad04557a7a0ece17db78040a7c/Try.Redis472.Services/TestService.cs#L25). No error message, no exception, no warnings...

**Comment by mgravell** [comment]
That project is targeting v1.2.6; I don't know the specific reasons why that site isn't working with that, but it also isn't something I really want to spend a massive amount of time debugging if the "use an up to date library" approach fixes it...?

**Comment by saciervo** [comment]
Isn't 1.2.6 the most recent one? https://www.nuget.org/packages/StackExchange.Redis.StrongName

**Comment by mgravell** [comment]
Well... no, not really; in v2 we fixed the "why the hell does strong-name exist" problem; the main SE.Redis package is now strong named; StackExchange.Redis.StrongName is essentially obsolete

**Comment by saciervo** [comment]
Alright, good to know. I just used the `Microsoft.Extensions.Caching.Redis` package because I read it somewhere in a MS or Azure documentation. That package still wraps the obsolete StrongName package.

I noticed that there is a newer package with a different name `Microsoft.Extensions.Caching.StackExchangeRedis` and according to [this SO answer](https://stackoverflow.com/questions/59847571/differences-between-microsoft-extensions-cashing-redis-and-microsoft-extensions) it's essentially the same, just newer and probably better maintained. Also it wraps the `StackExchange.Redis` package instead of the obsolete one.

So I just went back to my repo and replaced said packages and also updated all other packages to their newest version. But the problem still persists...

**Comment by saciervo** [comment]
So after further hours of debugging, it seems to be a problem with converting async methods with `.GetAwaiter().GetResult()`. I'll probably have some time again tomorrow night to finally track it down. 

@mgravell do you suspect already what the problem could be? Any recommendations to convert async calls? In the past I always did this via getting the awaiter and then the result as you see above.

**Comment by mgravell** [comment]
Is this a problem *in the SE-Redis library*? or in your own calling code? The reason I ask is that in terms of SE-Redis, it already provides a dual API, so: there's no reason to call an async method and then do a sync-over-async - you'd just call the sync method. If this is in the library, can you be more specific as to where?

But in terms of the actual question (of how to do "sync over async"), the generally preferred answer is simply "don't"; the longer answer is "don't; that'll hurt you in so many ways". If we're talking about consumer code, I'm happy to chime in there, but it *really, really* needs an example that we could look at, as context **really** matters here.

**Comment by saciervo** [comment]
Still not sure, the blocking is out of the way. That was definitely the `.GetAwaiter().GetResult()` thing. Now I use the non-async methods, I didn't notice them before. I do not use SE-Redis directly, only via `Microsoft.Extensions.Caching.Redis` package and their `IDistributedCache` interface.. It doesn't work with SSL at the moment, but I will try to reproduce it in the repo above tomorrow.

**Comment by devigo** [comment]
@saciervo Your code will deadlock. Try to replace `.GetAwaiter().GetResult()` with `.ConfigureAwait(false).GetAwaiter().GetResult()`. But it's better to avoid blocking async code.

More information here https://blog.stephencleary.com/2012/07/dont-block-on-async-code.html

**Comment by NickCraver** [comment]
The true fix here is: go full async, sync-over-async and the other way around are both are likely to lead to application doom. If we want tweaks in the upstream library on the sync vs. async, definitely file an issue so that they're aware! Given Redis is off-box though, you really _want_ async top to bottom here, FWIW.
