### ISSUE TITLE
SocketFailure because of network latency

### ISSUE THREAD

**Issue by KeyurRamoliya** [StackExchange/StackExchange.Redis#1769]
We have a Redis server deployed on Ubuntu VM on Azure. Whenever we try to connect it from other VMs(Windows) we are getting `SocketFailure`.

We know it is due to network latency on Azure because on other environments the same thing is working fine. We have tried different values for the `connectTimeout`. But the issue is still not resolved.

We are facing this issue with SSL mode only for non-SSL connection it is working fine.

Are there any other config options that we are missing here?

Please see the below logs from the Client(StackExchange.Redis).

```
REDISSERVERNAME:6379,allowAdmin=True,connectTimeout=15000,password=*****,ssl=True,sslProtocols=Tls12,abortConnect=False

Connecting REDISSERVERNAME:6379/Interactive...
BeginConnect: REDISSERVERNAME:6379
1 unique nodes specified
Configuring TLS
Requesting tie-break from REDISSERVERNAME:6379 > __Booksleeve_TieBreak...
Allowing endpoints 00:00:15 to respond...
Awaiting task completion, IOCP: (Busy=2,Free=998,Min=2,Max=1000), WORKER: (Busy=0,Free=2047,Min=2,Max=2047)
Not all tasks completed cleanly (from ReconfigureAsync#1748, timeout 15000ms), IOCP: (Busy=2,Free=998,Min=2,Max=1000), WORKER: (Busy=1,Free=2046,Min=2,Max=2047)
REDISSERVERNAME:6379 did not respond
Waiting for tiebreakers...
Awaiting task completion, IOCP: (Busy=2,Free=998,Min=2,Max=1000), WORKER: (Busy=1,Free=2046,Min=2,Max=2047)
Not all tasks completed cleanly (from NominatePreferredMaster#1985, timeout 50ms), IOCP: (Busy=2,Free=998,Min=2,Max=1000), WORKER: (Busy=1,Free=2046,Min=2,Max=2047)
REDISSERVERNAME:6379 failed to nominate (WaitingForActivation)
No masters detected
REDISSERVERNAME:6379: Standalone v2.0.0, master; keep-alive: 00:01:00; int: Connecting; sub: Connecting; not in use: DidNotRespond
REDISSERVERNAME:6379: int ops=0, qu=0, qs=0, qc=0, wr=0, socks=1; sub ops=0, qu=0, qs=0, qc=0, wr=0, socks=1
Circular op-count snapshot; int: 0 (0.00 ops/s; spans 10s); sub: 0 (0.00 ops/s; spans 10s)
Sync timeouts: 0; async timeouts: 0; fire and forget: 0; last heartbeat: -1s ago
resetting failing connections to retry...
retrying; attempts left: 2...
1 unique nodes specified
Requesting tie-break from REDISSERVERNAME:6379 > __Booksleeve_TieBreak...
Allowing endpoints 00:00:15 to respond...
Awaiting task completion, IOCP: (Busy=2,Free=998,Min=2,Max=1000), WORKER: (Busy=1,Free=2046,Min=2,Max=2047)
TLS connection established successfully using protocol: Tls12
Connected Interactive/REDISSERVERNAME:6379
Server handshake
Authenticating (password)
Setting client name: CLIENT_NAME
Auto-configure...
Sending critical tracer: Interactive/REDISSERVERNAME:6379
Writing to Interactive/REDISSERVERNAME:6379: ECHO
Flushing outbound buffer
Starting read
connection failed: REDISSERVERNAME:6379 (Subscription, SocketFailure): SocketFailure (0-read, 0-sent) on REDISSERVERNAME:6379/Subscription, Flushed/Faulted, last: SUBSCRIBE, origin: ReadFromPipe, outstanding: 4, last-read: 15s ago, last-write: 0s ago, keep-alive: 60s, state: ConnectedEstablishing, mgr: 8 of 10 available, last-heartbeat: never, global: 15s ago, v: 2.2.4.27433
> Unable to read data from the transport connection: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'..
> Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
connection failed: REDISSERVERNAME:6379 (Interactive, SocketFailure): SocketFailure (0-read, 0-sent) on REDISSERVERNAME:6379/Interactive, Flushed/Faulted, last: ECHO, origin: ReadFromPipe, outstanding: 9, last-read: 15s ago, last-write: 0s ago, keep-alive: 60s, state: ConnectedEstablishing, mgr: 8 of 10 available, last-heartbeat: never, global: 15s ago, v: 2.2.4.27433
> Unable to read data from the transport connection: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'..
> Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
Finished awaiting tasks, IOCP: (Busy=2,Free=998,Min=2,Max=1000), WORKER: (Busy=3,Free=2044,Min=2,Max=2047)
REDISSERVERNAME:6379 faulted: SocketFailure (0-read, 0-sent) on REDISSERVERNAME:6379/Interactive, Flushed/Faulted, last: ECHO, origin: ReadFromPipe, outstanding: 9, last-read: 15s ago, last-write: 0s ago, keep-alive: 60s, state: ConnectedEstablishing, mgr: 8 of 10 available, last-heartbeat: never, global: 15s ago, v: 2.2.4.27433
Waiting for tiebreakers...
All tasks are already complete
REDISSERVERNAME:6379 failed to nominate (Faulted)
> SocketFailure (0-read, 0-sent) on REDISSERVERNAME:6379/Interactive, Flushed/Faulted, last: ECHO, origin: ReadFromPipe, outstanding: 9, last-read: 15s ago, last-write: 0s ago, keep-alive: 60s, state: ConnectedEstablishing, mgr: 8 of 10 available, last-heartbeat: never, global: 15s ago, v: 2.2.4.27433
No masters detected
```

Client Code:

```csharp
using System;
using System.IO;
using System.Linq;
using System.Net.Security;
using System.Security.Cryptography.X509Certificates;
using System.Threading.Tasks;
using StackExchange.Redis;

namespace TestConsole
{
    internal static class Program
    {
        public static async Task Main()
        {
            var connectionString = @"REDISSERVERNAME:6379,password=*****,abortConnect=false,allowAdmin=true,ssl=true,sslHost=REDISSERVERNAME,sslProtocols=Tls12,connectTimeout=15000";
            var configOptions = ConfigurationOptions.Parse(connectionString);

            if (configOptions.Ssl)
            {
                configOptions.CertificateSelection += OptionsOnCertificateSelection;
                configOptions.CertificateValidation += ValidateServerCertificate;
            }

            var client = ConnectionMultiplexer.Connect(configOptions, new StreamWriter(Console.OpenStandardOutput()));
            client.GetDatabase().Ping();
            var db = client.GetDatabase(0);

            var start = DateTime.Now;

            Console.WriteLine();

            Show(client.GetCounters());

            var tasks = Enumerable.Range(0, 1000).Select(async i =>
            {
                int timeoutCount = 0;
                RedisKey key = i.ToString();
                for (int t = 0; t < 1000; t++)
                {
                    try
                    {
                        await db.StringIncrementAsync(key, 1);
                    }
                    catch (TimeoutException) { timeoutCount++; }
                }
                return timeoutCount;
            }).ToArray();

            await Task.WhenAll(tasks);
            int totalTimeouts = tasks.Sum(x => x.Result);
            Console.WriteLine("Total timeouts: " + totalTimeouts);
            Console.WriteLine();
            Show(client.GetCounters());

            var duration = DateTime.Now.Subtract(start).TotalMilliseconds;
            Console.WriteLine($"{duration}ms");

            Console.ReadLine();
        }

        private static void Show(ServerCounters counters)
        {
            Console.WriteLine("CA: " + counters.Interactive.CompletedAsynchronously);
            Console.WriteLine("FA: " + counters.Interactive.FailedAsynchronously);
            Console.WriteLine("CS: " + counters.Interactive.CompletedSynchronously);
            Console.WriteLine();
        }

        private static X509Certificate OptionsOnCertificateSelection(object s, string t, X509CertificateCollection local, X509Certificate remote, string[] a)
        {
            return new X509Certificate2(@"Certificate Path");
        }

        public static bool ValidateServerCertificate(object sender, X509Certificate certificate, X509Chain chain, SslPolicyErrors sslPolicyErrors)
        {

            if (RevocationMode == 0)
            {
                X509Certificate2 cert = new X509Certificate2(certificate);
                chain.ChainPolicy.RevocationMode = X509RevocationMode.NoCheck;
                chain.Build(cert);
            }
            const SslPolicyErrors ignoredErrors =
            SslPolicyErrors.RemoteCertificateChainErrors |  // self-signed
            SslPolicyErrors.RemoteCertificateNameMismatch;  // name mismatch
            if ((sslPolicyErrors & ~ignoredErrors) == SslPolicyErrors.None)
            {
                return true;
            }
            return false;
        }
    }
}
```

**Comment by philon-msft** [comment]
Hi @KeyurRamoliya, 6379 is the non-TLS port. For an SSL connection you want to use port 6380. In general, you don't need to specify the port. The appropriate port will be automatically selected based on the value of the 'ssl' ConfigurationOption.

**Comment by KeyurRamoliya** [comment]
@philon-msft - We have configured our Redis server on port 6379 for SSL. Due to that we are explicitly mentioning port in connection string.

Is there any chances of getting this behaviour because of port?

**Comment by philon-msft** [comment]
Yes to avoid potential problems, I'd recommend sticking with the default port configuration.

**Comment by KeyurRamoliya** [comment]
Surely, We can try that. But I don't think so port should create any problem here. As per redis server docs, they haven't mentioned anything like this.

https://redis.io/topics/encryption

Also, from logs above I am seeing like it is problem of socket disposal. Probably due network latency there might be some socket issue.

Do you have any idea on this?

**Comment by NickCraver** [comment]
@KeyurRamoliya 2 asks:
1. Can you please try v2.2.50? I've added a lot to connection logging
2. What environment is this in? Is it a self-hosted Redis server? I don't think there's any issues with v2.0 but it is a very old server version. I wonder if what you're hitting is related to the AUTH race also fixed in 2.2.50, and Redis is killing the socket in anger when hitting that race today.

**Comment by mudithaa** [comment]
I too see the RemoteCertificateChainErrors when working with Azure Redis Cache. 
I have updated the Nuget to 2.2.62 but no change in the behaviour. 

This is only happening on certain machines at the moment. 

@NickCraver where can I see these logs ?

**Comment by NickCraver** [comment]
@mudithaa When calling connect, you can pass a TextWriter into the method, that's where we write to while connecting - if you look at that after it provides more detail for what's happening when on the connection. It sounds though like this is a certificate error where the client isn't trusting the Azure's SSL certificate endpoint - that's a more global configuration issue on the system and makes more sense as to why you're seeing it on some machines and not others.

**Comment by NickCraver** [comment]
If we can get some more info here, very happy to reopen and add more advice - for now closing sans anything else to advise on.

**Comment by TimLovellSmith** [comment]
Breadcrumb remark! For anyone lost in the woods, and still seeing issues in 'NominatePreferredMaster' with the 50ms timeout, like this one, I'd strongly suggest you update to a more recent version of the library (such as latest and greatest, 2.6.48) to take advantage of many fixes to connection reliability that relate to that code path.
